import FOL.Tactics
import FOL.Nd
import FOL.Alpha
import FOL.Formula
import FOL.Binders
import FOL.Semantics
import FOL.FunctionUpdateIte
import FOL.List
import FOL.Sub.One.Rec.SubOneRecAdmits
import FOL.Sub.One.Rec.SubOneRecReplaceFree
import FOL.Sub.One.Ind.SubOneInd
import FOL.Sub.All.Rec.SubAllRecReplaceFree
import FOL.Sub.All.Rec.SubAllRecAdmits
import FOL.PredSub.One.Rec.PredSubOneRec
import FOL.PredSub.One.Ind.PredSubOneInd
import FOL.PredSub.All.Rec.PredSubAllRec
import FOL.PropSub.All.Rec.PropSubAllRec
import FOL.Margaris.Deduct
